import React, { useState, useMemo } from "react";
import { Search } from "lucide-react";
import { money } from "../utils.js";

export default function History({ historyIndex, loading, onDownload, onDelete }) {
  const [search, setSearch] = useState("");

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    if (!q) return historyIndex;
    return historyIndex.filter((item) =>
      [item.number, item.invoiceName, item.clientName, item.createdBy]
        .filter(Boolean)
        .some((field) => field.toLowerCase().includes(q)),
    );
  }, [historyIndex, search]);

  return (
    <div>
      <h1 className="text-[23px] font-bold text-ink mb-1">Invoice history</h1>
      <p className="text-slate text-[13.5px] mb-5">
        Every invoice generated by the team, with one-click re-download.
      </p>

      <div className="relative mb-4 max-w-sm">
        <Search
          size={15}
          className="absolute left-3 top-1/2 -translate-y-1/2 text-slate"
        />
        <input
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Search by name, number, or client…"
          className="w-full pl-9 pr-3 py-2 border border-line rounded-md text-[13px] bg-white"
        />
      </div>

      <div className="bg-white border border-line rounded-lg px-5.5 py-5">
        {loading ? (
          <div className="text-center py-12 text-slate">Loading…</div>
        ) : filtered.length === 0 ? (
          <div className="text-center py-12 text-slate">
            <div className="text-[17px] text-ink font-bold mb-1.5">
              {historyIndex.length === 0 ? "No invoices yet" : "No matches"}
            </div>
            <div>
              {historyIndex.length === 0
                ? "Generate your first invoice and it will show up here."
                : "Try a different search term."}
            </div>
          </div>
        ) : (
          <table className="w-full border-collapse text-[13px]">
            <thead>
              <tr>
                <th className="text-left text-[11px] uppercase text-slate px-2 py-2 border-b border-line">
                  Number
                </th>
                <th className="text-left text-[11px] uppercase text-slate px-2 py-2 border-b border-line">
                  Name
                </th>
                <th className="text-left text-[11px] uppercase text-slate px-2 py-2 border-b border-line">
                  Client
                </th>
                <th className="text-left text-[11px] uppercase text-slate px-2 py-2 border-b border-line">
                  Date
                </th>
                <th className="text-left text-[11px] uppercase text-slate px-2 py-2 border-b border-line">
                  Created by
                </th>
                <th className="text-right text-[11px] uppercase text-slate px-2 py-2 border-b border-line">
                  Total
                </th>
                <th className="border-b border-line"></th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((item) => (
                <tr key={item.number}>
                  <td className="px-2 py-2.5 border-b border-gray-100 font-mono text-tealdeep font-semibold">
                    {item.number}
                  </td>
                  <td className="px-2 py-2.5 border-b border-gray-100">
                    {item.invoiceName || (
                      <span className="text-gray-300">—</span>
                    )}
                  </td>
                  <td className="px-2 py-2.5 border-b border-gray-100">
                    {item.clientName}
                  </td>
                  <td className="px-2 py-2.5 border-b border-gray-100">
                    {item.invoiceDate || "—"}
                  </td>
                  <td className="px-2 py-2.5 border-b border-gray-100 text-[12.5px] text-slate">
                    {item.createdBy || "—"}
                  </td>
                  <td className="px-2 py-2.5 border-b border-gray-100 text-right font-mono">
                    {money(item.total)}
                  </td>
                  <td className="px-2 py-2.5 border-b border-gray-100">
                    <div className="flex gap-1.5 justify-end">
                      <button
                        onClick={() => onDownload(item, "pdf")}
                        className="text-[11.5px] px-2 py-1 border border-line rounded hover:border-teal hover:text-teal"
                      >
                        PDF
                      </button>
                      <button
                        onClick={() => onDownload(item, "xlsx")}
                        className="text-[11.5px] px-2 py-1 border border-line rounded hover:border-teal hover:text-teal"
                      >
                        Excel
                      </button>
                      <button
                        onClick={() => {
                          if (
                            confirm(
                              `Delete invoice ${item.number}? This can't be undone.`,
                            )
                          ) {
                            onDelete(item);
                          }
                        }}
                        className="text-[11.5px] px-2 py-1 border border-line rounded hover:border-red-400 hover:text-red-500"
                      >
                        X
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}
